package com.ciro.orderservice.mapper;

import com.ciro.orderservice.dto.OrderItemRequest;
import com.ciro.orderservice.dto.OrderItemResponse;
import com.ciro.orderservice.dto.OrderRequest;
import com.ciro.orderservice.dto.OrderResponse;
import com.ciro.orderservice.model.Order;
import com.ciro.orderservice.model.OrderItem;
import org.mapstruct.AfterMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

// componentModel = "spring" makes MapStruct register the generated implementation as a Spring
// @Component, so it can be constructor-injected like any other bean.
@Mapper(componentModel = "spring")
public interface OrderMapper
{
    // Request -> Entity. The client never sends these, so we keep MapStruct from mapping them:
    @Mapping(target = "id", ignore = true)         // generated by the DB (IDENTITY column)
    @Mapping(target = "createdAt", ignore = true)  // filled in by @CreationTimestamp on persist
    @Mapping(target = "status", constant = "PENDING")  // a new order always starts as PENDING (server-owned)
    Order toEntity(OrderRequest request);

    // Item-level mapping. "order" is the back-reference, wired later in linkItems (see below),
    // and "id" is DB-generated — both ignored to silence "unmapped target property" warnings.
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "order", ignore = true)
    OrderItem toItemEntity(OrderItemRequest request);

    OrderResponse toResponse(Order order);

    OrderItemResponse toItemResponse(OrderItem item);

    // Runs right after toEntity builds the Order. MapStruct populates the items list with setters
    // but never calls our addItem(), so the owning side (item.order) stays null and the FK would be
    // saved as null. This restores the bidirectional link by hand.
    @AfterMapping
    default void linkItems(@MappingTarget Order order)
    {
        if (order.getItems() != null)
        {
            order.getItems().forEach(item -> item.setOrder(order));
        }
    }
}
