services:
  order-postgres:
    image: postgres:16-alpine
    container_name: orderflow-order-postgres
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  inventory-postgres:
    image: postgres:16-alpine
    container_name: orderflow-inventory-postgres
    environment:
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
      POSTGRES_DB: inventory
    ports:
      - "5433:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  order_postgres_data:
  inventory_postgres_data: